server:
  port: 9393

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zoomcardb.cawtjgg5q64o.ap-south-1.rds.amazonaws.com/zoom_car
    username: root
    password: 12345678
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

  bezkoder:
    openapi:
      dev-url: http://localhost:8085
      prod-url: https://bezkoder-api.com




